DELETE FROM users;
ALTER TABLE users ALTER COLUMN id restart WITH 1;
ALTER TABLE items ALTER COLUMN id restart WITH 1;
ALTER TABLE bookings ALTER COLUMN id restart WITH 1;
ALTER TABLE comments ALTER COLUMN id restart WITH 1;
ALTER TABLE requests ALTER COLUMN id restart WITH 1;